### PR TITLE
Admin Functionality & Mobile Responsiveness Fix

### PR DESCRIPTION
**Pull request by emcooper**
#### What does this PR do?

1.  adds admin functionality:
- adds admin dashboard as root_path
- admin can change user role and delete users
- admin can delete wines
- admin can delete venues
- fixes admin broken links
2. adds mobile responsiveness to member profile 

#### Where should the reviewer start?
start with the admin controllers (base, admin, wine, venue, users) and the admin dashboard view
#### How should this be manually tested?
login as admin: 
username: admin
password: password

then navigate links from dashboard to test functionality above

#### Questions:
  - Do Migrations Need to be ran? no
  - Do Environment Variables need to be set? no
  - Any other deploy steps? bundle (added font-awesome gem)

### CODE REVIEW

**Comment by samanthagongora** [comment]
I pulled down on my computer and everything works. I am beginning to think about how deleting wines and venues will work when we aren't persisting them to the database. 

I think that for the Admin 'delete' users we have to have it keep the user in the database (inactivate them without deleting the information). 

Nitpick: 
if you wrap the admin cards in the following, each card will be the same size:

<div class="card small">
  <div class="card-content">
    **header content**
  </div>
</div>

**Comment by emcooper** [comment]
I thought we are persisting venues and wines, just not all their details? 

I'll change delete to deactivate.

**Comment by emcooper** [comment]
I made the change to deactivate instead of delete. I'm not sure what you mean by the header content wrap. Is that a class? If you can give me an example I can definitely add it.

**Comment by samanthagongora** [comment]
I think you are right about wines and venues. There will be something persisted (even if just code and name) when someone follows or reviews. 

About the header content: I am not sure why the div stuff didn't show up. Trying again with a code snippet.

```
      <div class="card small">
        <div class="card-content">
          <h4><i class="fa fa-users" aria-hidden="true"></i> <br><br>Manage Users</h4>
      </div>
    </div>
```

**Comment by emcooper** [comment]
Thanks for the snippet, I added that.

**Comment by samanthagongora** [comment]
Sweet, let's merge.

**Pull request merged**
