### PR TITLE
Venue & Wine reviews---Needs Convo and to be looked over

### PR DESCRIPTION
**Pull request by swdonovan**
Here is the reviews for wines and venues.  If we want this as a note taking-esque type app then easily this can be taken away from the respective pages easily but left in the user dashboard just as easily.

Not tested yet as that wasn't my concern but I will work on that as time passes but it won't be my focus until I know what we are doing with it.

#### Questions:
  - Do Migrations Need to be ran?
  - Do Environment Variables need to be set?
  - Any other deploy steps?

### CODE REVIEW

**Comment by swdonovan** [comment]
screen shot 2017-09-16 at 12 08 43 pm
Adjusted the styling for venues.  Added a back ground image but that can be changed....the color was giving me a headache.

**Comment by swdonovan** [comment]
--Alright so I fixed Travis CI problems, that was weird btw.  
--Then added a test for the reviews to make sure they were officially tested.  
--Above is a screen shot of the redone page that I stole the frame work from Ellen and used that as a basis, thanks Ellen :) .
--The back ground image looks like poop but I couldn't get a better one to work with out repeating the image.  

If there is anything else you think needs to be done let me know!

**Comment by emcooper** [comment]
The reviews look really good! Thanks for adding tests too.

The background is a cool pic but because it's so dark it hides the black text on a lot of pages. Also, on longer pages like the index the image ends and then it is just the pink again. I'm down for using it but maybe we can leave it off for now to make the development process easier on ourselves? We would need to go through and change a bunch of other styling so we might as well wait to do that until we make a final decision on it. We can change it back to white if the pink is annoying.  

Another idea: it could be a great background for the splash page (pre-login) since that will be a pretty simple page. 

Let me know what you think.

**Comment by swdonovan** [comment]
Good Idea....I opened up a new branch and noticed that it cut off and so I instantly removed it so I am definitely game to have it GONE lol.

**Comment by emcooper** [comment]
Awesome! I think this is ready to merge then.

**Pull request merged**
