### PR TITLE
Sg snooth api

### PR DESCRIPTION
**Pull request by samanthagongora**
#### What does this PR do?
    * Allows for API requests to Snooth Wines for index and show pages. Integrates with base functionality. Changes Wine table to only persist Snooth id and name.

#### Where should the reviewer start?
    * This changed a lot about how all wines function on the page. If you want to do a thorough review, I would login as each type of user and try to use all things related to wine:
        * follow a wine/unfollow a wine
        * review a wine
        * add a wine to a venue/remove a wine from a venue
        * View profile pages and check news feeds and follows

#### Questions:
  - Do Migrations Need to be ran? yes
  - Do Environment Variables need to be set? no

### CODE REVIEW

**Comment by emcooper** [comment]
So unfortunately, I'm still seeing the following behavior:
- when you review or follow a wine, and then click on the wine name in the feed, you go to a random wine page 
- when you follow a wine, you are redirected to random wine page

I did a rake db:reset. Was this working for you?

**Comment by samanthagongora** [comment]
Im sorry. I just missed those bugs. This branch should be good.

**Comment by emcooper** [comment]
the following redirect issue seems to be fixed 👍 , however I'm still noticing the following:
- when you review or follow a wine, and then click on the wine name in the feed, you go to a random wine page

and a new one  :
- when you review a wine and select a venue, the wine name doesn't appear in the news feed. When you don't select a venue it does.

😢 Sorry, I know this is terrible.

**Comment by swdonovan** [comment]
The going to a random wine when clicked on from the stream feed.-->>  Take out the link_to in the views and don't allow them to go for now.  The way that it is input and/or called from stream (lets just blow up stream and/or take it out)  would have to change to make that link work.  I will try to take a look at it, but for the bug just take out the link to in the view would be my approach.

**Comment by swdonovan** [comment]
this actually works for me on my browser when I the user do it, but not when i click on one from the seed data

**Pull request merged**
