### PR TITLE
Emc user profile 2

### PR DESCRIPTION
**Pull request by emcooper**
#### What does this PR do?
- Makes the root path for regular members redirect to user profile
- styles/organizes user profile
- adds followed wines/venues to user profile
- creates followed_wines relationship for user
#### How should this be manually tested?
sign in, you should be directed to user profile and see all of the things described above
#### Questions:
  - Do Migrations Need to be ran?
no
  - Do Environment Variables need to be set?
no
  - Any other deploy steps?
no

### CODE REVIEW

**Comment by samanthagongora** [comment]
Can you add a redirect for the root path? It is still going to a blank page. Other than that, I think the code looks great. 

Minor nitpick:
The profile page has a few elements that become off center or spill outside of a box when viewed on mobile.

**Comment by emcooper** [comment]
That's weird, for me the root path goes to the user profile. What specifically are you clicking/typing in to lead to the blank page?

**Comment by emcooper** [comment]
I think the mobile issues would be cool to look into if we have time later in the project. This is using materialize's grid system so we might have to move away from materialize if we want to really fine tune it.

**Comment by swdonovan** [comment]
This is some bad ass work @emcooper. We can get the mobile stuff working next week but we might want to make a card for it and make it a priority to be done before shipping.  What does everyone think about pushing this to master with that bug on just mobile?? Keep in mind that this will be getting pushed to heroku at some point.  I am good with it as long as a pivotal card gets made, we have other styling issues on that branch already.  Great convo btw its awesome and was actually helpful

**Comment by emcooper** [comment]
Yeah I'm good with just making a pivotal card 👍  I'd like to fix the routing error before merging though, since it should be a quick fix. We can talk about it at standup since I'm not really sure where it's occurring.

**Pull request merged**
